// Generated by gencpp from file test/multiplier.msg
// DO NOT EDIT!


#ifndef TEST_MESSAGE_MULTIPLIER_H
#define TEST_MESSAGE_MULTIPLIER_H

#include <ros/service_traits.h>


#include <test/multiplierRequest.h>
#include <test/multiplierResponse.h>


namespace test
{

struct multiplier
{

typedef multiplierRequest Request;
typedef multiplierResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct multiplier
} // namespace test


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::test::multiplier > {
  static const char* value()
  {
    return "a7d7d7065d45755acef7d4dcf908162a";
  }

  static const char* value(const ::test::multiplier&) { return value(); }
};

template<>
struct DataType< ::test::multiplier > {
  static const char* value()
  {
    return "test/multiplier";
  }

  static const char* value(const ::test::multiplier&) { return value(); }
};


// service_traits::MD5Sum< ::test::multiplierRequest> should match
// service_traits::MD5Sum< ::test::multiplier >
template<>
struct MD5Sum< ::test::multiplierRequest>
{
  static const char* value()
  {
    return MD5Sum< ::test::multiplier >::value();
  }
  static const char* value(const ::test::multiplierRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::test::multiplierRequest> should match
// service_traits::DataType< ::test::multiplier >
template<>
struct DataType< ::test::multiplierRequest>
{
  static const char* value()
  {
    return DataType< ::test::multiplier >::value();
  }
  static const char* value(const ::test::multiplierRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::test::multiplierResponse> should match
// service_traits::MD5Sum< ::test::multiplier >
template<>
struct MD5Sum< ::test::multiplierResponse>
{
  static const char* value()
  {
    return MD5Sum< ::test::multiplier >::value();
  }
  static const char* value(const ::test::multiplierResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::test::multiplierResponse> should match
// service_traits::DataType< ::test::multiplier >
template<>
struct DataType< ::test::multiplierResponse>
{
  static const char* value()
  {
    return DataType< ::test::multiplier >::value();
  }
  static const char* value(const ::test::multiplierResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // TEST_MESSAGE_MULTIPLIER_H
